/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengl.GL;
import org.lwjgl.opengl.GL11;

import static org.lwjgl.opengl.GL11.*;

import org.example.game.Player;
import org.example.game.World;
import org.example.interfaces.implementations.Input;

public class App {

    static Player player;
    static World world;
    static Input input;

    public static void main(String[] args) {
        if (!GLFW.glfwInit()) {
            throw new IllegalStateException("GLFW init failed");
        }

        long window = GLFW.glfwCreateWindow(800, 600, "PAC-MAN", 0, 0);

        GLFW.glfwMakeContextCurrent(window);

        GL.createCapabilities();
        glEnable(GL_TEXTURE_2D);

        input = new Input(window);
        player = new Player(100, 100);
        world = new World(20, 15);

        glMatrixMode(GL_PROJECTION);
        glLoadIdentity();
        glOrtho(0, 800, 600, 0, -1, 1);
        glMatrixMode(GL_MODELVIEW);
        glLoadIdentity();
        glDisable(GL_DEPTH_TEST);

        double lastTime = GLFW.glfwGetTime();

        while (!GLFW.glfwWindowShouldClose(window)) {
            double now = GLFW.glfwGetTime();
            double delta = now - lastTime;
            lastTime = now;

            player.update(delta, input);

            // Render
            glClear(GL_COLOR_BUFFER_BIT);

            // Set up orthographic projection for 2D rendering
            GL11.glMatrixMode(GL11.GL_PROJECTION);
            GL11.glLoadIdentity();
            GL11.glOrtho(0, 640, 480, 0, -1, 1);
            GL11.glMatrixMode(GL11.GL_MODELVIEW);
            GL11.glLoadIdentity();

            // Disable textures for solid color rendering

            world.render();

            player.render();

            org.lwjgl.glfw.GLFW.glfwSwapBuffers(window);
            org.lwjgl.glfw.GLFW.glfwPollEvents();
        }

        GLFW.glfwTerminate();
    }
}
