/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.example.game.Player;
import org.example.game.World;
import org.example.interfaces.InputState;

class PlayerTest {
    private World world = new World(20, 15);

    @Test
    void playerInitialPositionTest() {
        Player player = new Player(100, 100, world, false);
        assertEquals(100, player.x);
        assertEquals(100, player.y);
    }

    @Test
    void playerMoveRightTest() {
        Player player = new Player(100, 100, world, false);
        float initialX = player.x;

        InputState input = new InputState() {

            @Override
            public boolean isUp() {
                return false;
            }

            @Override
            public boolean isDown() {
                return false;
            }

            @Override
            public boolean isLeft() {
                return false;
            }

            @Override
            public boolean isRight() {
                return true;
            }

            @Override
            public boolean isEnter() {
                return false;
            }

            @Override
            public boolean isEscapePressed() {
                return false;
            }
            
        };
        player.update(1.0, input); // Simulate movement for 1 second

        // Without collision, x should increase (speed = 200px/s)
        assertTrue(player.x >= initialX);
    }

    @Test
    void playerInitialDirectionTest() {
        Player player = new Player(100, 100, world, false);
        InputState input = new InputState() {
            @Override
            public boolean isUp() { return false; }
            @Override
            public boolean isDown() { return false; }
            @Override
            public boolean isLeft() { return false; }
            @Override
            public boolean isRight() { return false; }
            @Override
            public boolean isEnter() { return false; }
            @Override
            public boolean isEscapePressed() { return false; }
        };
        player.update(0.1, input);
        // Player should exist and not throw exception
        assertNotNull(player);
    }

    @Test
    void playerSpeedConstantTest() {
        Player player = new Player(100, 100, world, false);
        assertEquals(200f, player.speed);
    }

    @Test
    void playerSizeConstantTest() {
        Player player = new Player(100, 100, world, false);
        assertEquals(32f, player.width);
        assertEquals(32f, player.height);
    }

    @Test
    void playerDefaultColorTest() {
        Player player = new Player(100, 100, world, false);
        assertEquals(1.0f, player.r);
        assertEquals(1.0f, player.g);
        assertEquals(0.0f, player.b);
    }
}
