/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.example.game.Player;
import org.example.interfaces.implementations.Input;

class PlayerTest {
    @Test
    void appHasAGreeting() {
        Player player = new Player(100, 100);
        player.update(20, new Input(0));
    }
}
